# Generated by Django 3.0.4 on 2022-04-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=264, unique=True),
        ),
    ]
